version: "3.7"

services:
  web:
    build:
      context: ./docker
      dockerfile: ${MAGENTO2_PHP_DOCKERFILE}
    volumes:
      - .:/data
      - ./docker/apache2.conf:/etc/apache2/conf.d/local.conf
      - ./docker/php.ini:/etc/php7/conf.d/99_docker.ini
    links:
      - mariadb
    networks:
      default:
        ipv4_address: 172.21.1.2

  mariadb:
    image: mariadb:10.4.18
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: magento
    networks:
      default:
        ipv4_address: 172.21.1.3

  elastic:
    image: elasticsearch:7.12.0
    networks:
      default:
        ipv4_address: 172.21.1.4
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

volumes:
  mariadb:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.21.1.0/24
